/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZaJbFe4WrxO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Button } from "@/components/ui/button"

export function TransactionTesting() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-background">
      <h1 className="text-3xl font-bold mb-8">Transactions QA</h1>
      <Tabs defaultValue="erc20">
        <TabsList className="grid grid-cols-3 gap-4">
          <TabsTrigger value="erc20">ERC-20 Transfer</TabsTrigger>
          <TabsTrigger value="erc721">ERC-721 Mint</TabsTrigger>
          <TabsTrigger value="eth">ETH Transfer</TabsTrigger>
        </TabsList>
        <TabsContent value="erc20">
          <div className="grid grid-cols-2 gap-4">
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              EoA transacting on Base
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              EoA transacting on Base Sepolia
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet transacting on Base
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet transacting on Base Sepolia
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet transacting on Base, sponsored
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet transacting on Base Sepolia, sponsored
            </Button>
          </div>
        </TabsContent>
        <TabsContent value="erc721">
          <div className="grid grid-cols-2 gap-4">
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              EoA minting on Base
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              EoA minting on Base Sepolia
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet minting on Base
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet minting on Base Sepolia
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet minting on Base, sponsored
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet minting on Base Sepolia, sponsored
            </Button>
          </div>
        </TabsContent>
        <TabsContent value="eth">
          <div className="grid grid-cols-2 gap-4">
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              EoA transferring ETH on Base
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              EoA transferring ETH on Base Sepolia
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet transferring ETH on Base
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet transferring ETH on Base Sepolia
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet transferring ETH on Base, sponsored
            </Button>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Smart Wallet transferring ETH on Base Sepolia, sponsored
            </Button>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  )
}
